version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/usr/src/app
    command: npm start
    # environment:
    #   - MONGO_URI=mongodb://host.docker.internal:27017/content-moderation
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27018/content-moderation
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    command: npm start

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: